### ISSUE TITLE
fmodel export uemodel of mesh, no material when drag in ue5.4

### ISSUE THREAD

**Issue by AlbieRWang** [h4lfheart/UEFormat#10]
i use fmodel4.4.3.6&ue5.4.4,but there is no material when i import uemodel
![image](https://github.com/user-attachments/assets/25f4577f-3341-47a7-bffe-b29f206982b4)

**Comment by halfuwu** [comment]
send the umodel files here please !!

**Comment by AlbieRWang** [comment]
> send the umodel files here please !!

[Foxe.zip](https://github.com/user-attachments/files/16944155/Foxe.zip)
tks,check this if u spare

**Comment by halfuwu** [comment]
![image](https://github.com/user-attachments/assets/5680b497-4957-4a91-9d14-c7d2566470c9)
![image](https://github.com/user-attachments/assets/2fd50717-03f4-4da2-bd02-8f0b7d303d1c)

idk man the materials are right there

if you're talking about the textures not being there, that's not how it works, do the mats yourself
