### ISSUE TITLE
struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by xzenocrimzie** [h4lfheart/UEFormat#14]
![image](https://github.com/user-attachments/assets/a1f68ebb-c477-4ba1-8f6a-d4f853634d64)
Version of UEFormat: Latest
Version of Blender: 4.1.1

error: struct.error: unpack requires a buffer of 4 bytes

Unfortunately unpacking this model yields this error. I've included it here for debugging.
[FemaleM_Face06_Seq.zip](https://github.com/user-attachments/files/18176195/FemaleM_Face06_Seq.zip)

Is the plugin incapable of handling models with shape keys?

**Comment by h4lfheart** [comment]
seems like the morph targets for lod 2 are serialized to a count of 47, but the 47 morphs aren't actually serialized, oversight in serialization code on my part, should now be fixed in latest cue4parse

https://github.com/FabianFG/CUE4Parse/commit/5bcd3af7b82a8ce802f72285721a81806ee0cca7

**Comment by h4lfheart** [comment]
of course make sure to re-export when this cue4parse change is pushed to fmodel
